In [1]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [3]:
import pandas as pd
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [6]:
model = svm.SVC(kernel = 'rbf', C = 30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

In [7]:
from sklearn.model_selection import cross_val_score

In [8]:
cross_val_score(svm.SVC(kernel= 'linear', C= 10, gamma = 'auto'), iris.data, iris.target, cv =5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 10, gamma = 'auto'), iris.data, iris.target, cv =5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [11]:
cross_val_score(svm.SVC(kernel= 'rbf', C= 20, gamma = 'auto'), iris.data, iris.target, cv =5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
import numpy as np
kernels =['rbf', 'linear']
C= [1, 10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel= kval, C = cval, gamma = 'auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [15]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma = 'auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'kernel']
    
}, cv= 5, return_train_score = False)
clf.fit(iris.data, iris.target)
clf.cv_results_

C:\Users\Archita Shrivastava\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Archita Shrivastava\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Archita Shrivastava\anaconda3\lib\site-packages\sklearn\svm\_base.py", line 180, in fit
    self._validate_params()
  File "C:\Users\Archita Shrivastava\anaconda3\lib\site-packages\sklearn\base.py", line 581, in _validate_params
    validate_parameter_constraints(


{'mean_fit_time': array([0.00315433, 0.00064583, 0.00153961, 0.0004045 , 0.00118957,
        0.00040364]),
 'std_fit_time': array([0.0004828 , 0.00053241, 0.0005279 , 0.00049542, 0.00038086,
        0.00049437]),
 'mean_score_time': array([0.00167828, 0.        , 0.00080538, 0.        , 0.00060244,
        0.        ]),
 'std_score_time': array([0.00084213, 0.        , 0.00040602, 0.        , 0.00049199,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'kernel', 'rbf', 'kernel', 'rbf', 'kernel'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'kernel'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'kernel'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'kernel'}],


In [16]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.003154      0.000483         0.001678        0.000842       1   
1       0.000646      0.000532         0.000000        0.000000       1   
2       0.001540      0.000528         0.000805        0.000406      10   
3       0.000405      0.000495         0.000000        0.000000      10   
4       0.001190      0.000381         0.000602        0.000492      20   
5       0.000404      0.000494         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       kernel   {'C': 1, 'kernel': 'kernel'}                NaN   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       kernel  {'C': 10, 'kernel': 'kernel'}                NaN   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       kernel  {'C': 20, 'kernel': 'kernel'}                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                NaN                NaN                NaN                NaN   
2                1.0           0.966667           0.966667                1.0   
3                NaN                NaN                NaN                NaN   
4                1.0           0.900000           0.966667                1.0   
5                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1              NaN             NaN                4  
2         0.980000        0.016330                1  
3              NaN             NaN                4  
4         0.966667        0.036515                3  
5              NaN             NaN                4

In [18]:
df[['param_C', 'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       kernel              NaN
2      10          rbf         0.980000
3      10       kernel              NaN
4      20          rbf         0.966667
5      20       kernel              NaN

In [19]:
clf.best_score_

0.9800000000000001

In [20]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [23]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma = 'auto'),{
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
    },
    cv = 5,
    return_train_score = False,
    n_iter = 2
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000

In [24]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [29]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma = 'auto'),
        'params' : {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear']
        }
        
    },
    'random_forest':{
            'model': RandomForestClassifier(),
            'params': {
                'n_estimators' : [1,5,10]
            }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver = 'liblinear', multi_class = 'auto'),
        'params':{
            'C': [1,5,10]
            
        }
    }
    
}

In [31]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score = False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params' : clf.best_params_
    })

In [32]:
df = pd.DataFrame(scores, columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}